"""Add missing tables

Revision ID: d3619e12cd53
Revises: 3ad1bbdefd9b
Create Date: 2026-07-29 02:32:37.079205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3619e12cd53'
down_revision: Union[str, None] = '3ad1bbdefd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.alter_column('input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('transcript',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('tokens_in',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::jsonb"))
        batch_op.alter_column('tokens_out',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::jsonb"))

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_pending'), postgresql_where="((status)::text = 'pending'::text)")
        batch_op.create_unique_constraint('uq_approval_unique_pending', ['subject_type', 'subject_id'])

    with op.batch_alter_table('campaign_steps', schema=None) as batch_op:
        batch_op.alter_column('send_condition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.create_unique_constraint(batch_op.f('uq_campaign_steps_campaign_id'), ['campaign_id', 'step_index'])

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
        batch_op.alter_column('attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.create_unique_constraint(batch_op.f('uq_events_provider_event_id'), ['provider_event_id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_messages_campaign_id_campaigns'), 'campaigns', ['campaign_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_template_id_templates'), 'templates', ['template_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_contact_id_contacts'), 'contacts', ['contact_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_campaign_id_campaign_steps'), 'campaign_steps', ['campaign_id', 'step_index'], ['campaign_id', 'step_index'], ondelete='CASCADE')

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('from_email',
               existing_type=sa.TEXT(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
        batch_op.alter_column('confidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('step_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.alter_column('variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('step_index',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=postgresql.CITEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('confidence',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('from_email',
               existing_type=postgresql.CITEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('changes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_campaign_id_campaign_steps'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_template_id_templates'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_campaign_id_campaigns'), type_='foreignkey')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_events_provider_event_id'), type_='unique')
        batch_op.alter_column('payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('attributes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('email',
               existing_type=postgresql.CITEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('campaign_steps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_campaign_steps_campaign_id'), type_='unique')
        batch_op.alter_column('send_condition',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_approval_unique_pending', type_='unique')
        batch_op.create_index(batch_op.f('ix_approvals_pending'), ['subject_type', 'subject_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.alter_column('tokens_out',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::jsonb"))
        batch_op.alter_column('tokens_in',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::jsonb"))
        batch_op.alter_column('transcript',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('output',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('input',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    op.create_table('settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###